apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: rollouts-demo-vsvc
  namespace: rollouts
spec:
  gateways:
  - rollouts-demo-gateway
  hosts:
  - "*" # eks에서 LB가 자동 생성되고 hostname을 받기 때문에, 여기서는 * 로 처리해준다.
  http:
  - name: primary
    route:
    - destination:
        host: rollouts-demo-stable
      weight: 100
    - destination:
        host: rollouts-demo-canary
      weight: 0
